// This should throw an exception
function main() {  
  println(1 / 0);  
}
